on:
  workflow_dispatch:
    inputs:
      apple_id:
        required: true
      apple_password:
        required: true
      file_name:
        required: true
      ipa_base64:
        description: 'The uploaded file payload encoded in text string'
        required: true

jobs:
  sign_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Convert the file string back into a functional application binary 
    - name: Reconstruct Uploaded Application File
      run: |
        echo "${{ github.event.inputs.ipa_base64 }}" | base64 --decode > input_app.ipa
        echo "Successfully unpacked: ${{ github.event.inputs.file_name }}"
